### ISSUE TITLE
Remaking diagnostic PDFs each time

### ISSUE THREAD

**Issue by kdharris101** [reillytilbury/coppafish#102]
The diagnostic PDFs are a great feature, but it seems like it is recreating them for every part of the pipeline, every time the code is run, even if they already exist.  For example see below.

```console
(coppafish) kenneth@Zaldoc:~/iss/daphne$ python -m coppafish daphne.ini
/home/kenneth/git/coppafish/coppafish/pipeline/run.py:145: NotebookPageWarning: Notebook already contains page: basic_info
  warnings.warn('basic_info', utils.warnings.NotebookPageWarning)
/home/kenneth/git/coppafish/coppafish/pipeline/run.py:175: NotebookPageWarning: Notebook already contains page: scale
  warnings.warn('scale', utils.warnings.NotebookPageWarning)
/home/kenneth/git/coppafish/coppafish/pipeline/run.py:203: NotebookPageWarning: Notebook already contains page: extract
  warnings.warn('extract', utils.warnings.NotebookPageWarning)
/home/kenneth/git/coppafish/coppafish/pipeline/run.py:204: NotebookPageWarning: Notebook already contains page: extract_debug
  warnings.warn('extract_debug', utils.warnings.NotebookPageWarning)
/home/kenneth/git/coppafish/coppafish/pipeline/run.py:233: NotebookPageWarning: Notebook already contains page: filter
  warnings.warn('filter', utils.warnings.NotebookPageWarning)
/home/kenneth/git/coppafish/coppafish/pipeline/run.py:264: NotebookPageWarning: Notebook already contains page: find_spots
  warnings.warn('find_spots', utils.warnings.NotebookPageWarning)
/home/kenneth/git/coppafish/coppafish/pipeline/run.py:365: NotebookPageWarning: Notebook already contains page: register
  warnings.warn('register', utils.warnings.NotebookPageWarning)
/home/kenneth/git/coppafish/coppafish/pipeline/run.py:366: NotebookPageWarning: Notebook already contains page: register_debug
  warnings.warn('register_debug', utils.warnings.NotebookPageWarning)
Creating Diagnostic PDF:  30%|████████████████████████▌                                                         | 3/10 [00:00<00:00, 54.26section/s, Extract]^CTraceback (most recent call last):
  File "/home/kenneth/anaconda3/envs/coppafish/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/kenneth/anaconda3/envs/coppafish/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/kenneth/git/coppafish/coppafish/__main__.py", line 44, in <module>
    run_pipeline(sys.argv[1])
  File "/home/kenneth/git/coppafish/coppafish/pipeline/run.py", line 60, in run_pipeline
    BuildPDF(nb, auto_open=False)
  File "/home/kenneth/git/coppafish/coppafish/plot/pdf/base.py", line 125, in __init__
    figs = self.create_pixel_value_hists(
  File "/home/kenneth/git/coppafish/coppafish/plot/pdf/base.py", line 496, in create_pixel_value_hists
    for pixel_value in range(pixel_max + 1):
KeyboardInterrupt
Creating Diagnostic PDF:  30%|████████████████████████▌                                                         | 3/10 [00:04<00:11,  1.60s/section, Extract]
```

**Comment by paulshuker** [comment]
Hello, the PDF must re-create itself after a new page gets added, but I will reduce the amount of times the build PDF gets called so it does not slow things down too much!

**Comment by kdharris101** [comment]
But can it be so that if a part of the pipeline has already run, it doesn't rerun PDF creation for that part?  If this requires saving a different PDF file for every part of the pipeline that is OK.  

Otherwise every time you rerun on a notebook, it will recreate the extract PDF, which takes a long time.

**Comment by paulshuker** [comment]
Okay, for simplicity I could save a new PDF for each coppafish section, or is the single document preferred?

**Comment by kdharris101** [comment]
I don't think it really matters whether the final output is one PDF file or multiple PDF files. 

But if saving a separate file for every section is easier, let's do that.  In particular, you could make saving the PDF the last thing that a pipeline section does before saving the notebook.  

Then in the main pipeline, if a notebook section exists it skips over that part of the pipeline including writing the PDF.

Having separate files for each pipeline section might reduce the chance confusion you get from appending to existing files rather than creating a new one for each section.
